import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Multiplayer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className={styles['game-container']} />
      <div className={styles['player-info']}>
        <div>
          <label htmlFor='player-name'>Your Name</label>
          <input id='player-name' maxLength={10} type='text' />
        </div>

        <div>
          <button id='player-color'>Change Color</button>
        </div>
      </div>
    </div>
  )
}

export default Home
